# Generated by Django 6.0 on 2025-12-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigIntegerField(default=7406831870165811200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigIntegerField(default=7406831870165811200, primary_key=True, serialize=False),
        ),
    ]
